spring.application.name=Road2CS

#Hide internal errors on response
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-path=never

#Swagger API properties#
#Swagger url
springdoc.swagger-ui.path=/swagger-ui.html

#Raw JSON Swagger path
springdoc.api-docs.path=/api-docs

#Enable/disable Swagger UI
springdoc.swagger-ui.enabled=true