spring.application.name=Road2CS

#Hide internal errors on response
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-path=never